# Generated by Django 5.2.1 on 2025-05-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='discount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
