# Generated by Django 5.1.1 on 2025-05-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipe',
            new_name='Recipe',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_desc',
            new_name='recipe_desc',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_image',
            new_name='recipe_image',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_name',
            new_name='recipe_name',
        ),
    ]
