# Generated by Django 5.1.1 on 2025-04-07 14:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='project_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='project_title', unique=True),
        ),
    ]
